package order.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "orders")
@Builder
@AllArgsConstructor
public class Order {

    @DynamoDBHashKey
    private String id;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private Date updatedAt;

//    @DynamoDBAttribute
//    private List<Item> items;

//    public void addItem(Item item) {
//        items.add(item);
//    }
}